// src/config.rs – compile-time firmware configuration
//
// All values originate from the user's .env file (loaded by build.rs) and are
// resolved at compile time via env!() / option_env!(). Runtime Wi-Fi pairing
// credentials are stored separately in NVS by wifi.rs.
//
// To add a new sensor type (temperature, humidity, pH, etc.) in the future,
// add a corresponding sub-struct here and extend .env.example with the
// relevant PLANTFRIEND_* variables.

// Certificate byte arrays generated by build.rs from the configured cert files.
// When no certs were configured, all entries are None.
include!(concat!(env!("OUT_DIR"), "/certs.rs"));

use plantfriend_core::sensors::DigitalInputLiquidSensorConfig;

/// Top-level configuration bundle available throughout the firmware.
pub struct Config {
    pub wifi: WifiConfig,
    pub mqtt: MqttConfig,
    pub sensor: SensorConfig,
    pub publish: PublishConfig,
    pub ha: HaConfig,
    pub ota: OtaConfig,
}

pub struct WifiConfig {
    /// Optional bootstrap SSID (used only when no paired credentials exist).
    pub bootstrap_ssid: Option<&'static str>,
    /// Optional bootstrap password.
    pub bootstrap_password: Option<&'static str>,
    /// Optional AP SSID override for pairing mode.
    pub pairing_ap_ssid: Option<&'static str>,
    /// SoftAP channel used during pairing mode.
    pub pairing_ap_channel: u8,
    /// Maximum number of stations that can connect to the setup AP.
    pub pairing_ap_max_connections: u16,
}

pub struct MqttConfig {
    /// Full broker URI including scheme and port.
    /// Supported schemes: mqtt://, mqtts://, mqtt5://, mqtt5s://
    pub broker_uri: &'static str,
    /// Optional broker username (empty string = unauthenticated).
    pub username: &'static str,
    /// Optional broker password.
    pub password: &'static str,
    /// MQTT client identifier (must be unique on the broker).
    pub client_id: &'static str,
    /// TLS configuration – None when plain MQTT is used.
    pub tls: Option<TlsConfig>,
}

/// Certificate material embedded at build time.
///
/// Set the corresponding PLANTFRIEND_MQTT_*_PATH variables in .env to enable.
/// Leave all three variables empty for plain-text MQTT.
pub struct TlsConfig {
    /// DER or PEM-encoded CA certificate used to verify the broker.
    pub ca_cert: Option<&'static [u8]>,
    /// Client certificate for mutual TLS (mTLS). Must accompany `client_key`.
    pub client_cert: Option<&'static [u8]>,
    /// Client private key for mutual TLS.
    pub client_key: Option<&'static [u8]>,
}

/// Liquid-level sensor hardware parameters.
pub struct SensorConfig {
    /// GPIO number wired to the sensor's OUTPUT pin.
    pub gpio_pin: u32,
    /// Shared digital-input sensor behavior used across firmware targets.
    pub logic: DigitalInputLiquidSensorConfig,
}

/// State-publishing timing.
pub struct PublishConfig {
    /// Heartbeat interval in milliseconds. 0 = on-change only.
    pub interval_ms: u64,
}

/// Home Assistant auto-discovery metadata.
pub struct HaConfig {
    /// HA MQTT discovery prefix (usually "homeassistant").
    pub discovery_prefix: &'static str,
    /// Unique device ID used in all discovery topics.
    pub device_id: &'static str,
    /// Human-readable device name shown in HA UI.
    pub device_name: &'static str,
    /// MQTT topic to which the sensor state is published.
    pub state_topic: &'static str,
    /// MQTT topic for LWT availability messages.
    pub availability_topic: &'static str,
}

/// OTA update behavior.
pub struct OtaConfig {
    /// Optional URL to an OTA app binary.
    pub firmware_url: Option<&'static str>,
    /// Enables automatic OTA apply on boot when a URL is configured.
    pub auto_apply_on_boot: bool,
}

impl Config {
    /// Construct the firmware configuration from compile-time environment
    /// variables.  Panics at compile time if required variables are missing.
    pub fn load() -> Self {
        let tls =
            if MQTT_CA_CERT.is_some() || MQTT_CLIENT_CERT.is_some() || MQTT_CLIENT_KEY.is_some() {
                Some(TlsConfig {
                    ca_cert: MQTT_CA_CERT,
                    client_cert: MQTT_CLIENT_CERT,
                    client_key: MQTT_CLIENT_KEY,
                })
            } else {
                None
            };

        Config {
            wifi: WifiConfig {
                bootstrap_ssid: option_env!("PLANTFRIEND_WIFI_BOOTSTRAP_SSID").and_then(non_empty),
                bootstrap_password: option_env!("PLANTFRIEND_WIFI_BOOTSTRAP_PASSWORD")
                    .and_then(non_empty),
                pairing_ap_ssid: option_env!("PLANTFRIEND_PAIRING_AP_SSID").and_then(non_empty),
                pairing_ap_channel: option_env!("PLANTFRIEND_PAIRING_AP_CHANNEL")
                    .map(parse_u8)
                    .unwrap_or(1),
                pairing_ap_max_connections: option_env!("PLANTFRIEND_PAIRING_AP_MAX_CONNECTIONS")
                    .map(parse_u16)
                    .unwrap_or(4),
            },
            mqtt: MqttConfig {
                broker_uri: env!("PLANTFRIEND_MQTT_BROKER_URI"),
                username: option_env!("PLANTFRIEND_MQTT_USERNAME").unwrap_or(""),
                password: option_env!("PLANTFRIEND_MQTT_PASSWORD").unwrap_or(""),
                client_id: env!("PLANTFRIEND_MQTT_CLIENT_ID"),
                tls,
            },
            sensor: SensorConfig {
                gpio_pin: parse_u32(env!("PLANTFRIEND_SENSOR_GPIO")),
                logic: DigitalInputLiquidSensorConfig {
                    active_high: parse_bool(env!("PLANTFRIEND_SENSOR_ACTIVE_HIGH")),
                    debounce_ms: parse_u64(env!("PLANTFRIEND_SENSOR_DEBOUNCE_MS")),
                },
            },
            publish: PublishConfig {
                interval_ms: parse_u64(env!("PLANTFRIEND_PUBLISH_INTERVAL_MS")),
            },
            ha: HaConfig {
                discovery_prefix: env!("PLANTFRIEND_HA_DISCOVERY_PREFIX"),
                device_id: env!("PLANTFRIEND_HA_DEVICE_ID"),
                device_name: env!("PLANTFRIEND_HA_DEVICE_NAME"),
                state_topic: env!("PLANTFRIEND_MQTT_STATE_TOPIC"),
                availability_topic: env!("PLANTFRIEND_MQTT_AVAILABILITY_TOPIC"),
            },
            ota: OtaConfig {
                firmware_url: option_env!("PLANTFRIEND_OTA_URL").and_then(non_empty),
                auto_apply_on_boot: option_env!("PLANTFRIEND_OTA_AUTO_APPLY")
                    .map(parse_bool)
                    .unwrap_or(false),
            },
        }
    }
}

// ── Compile-time parsing helpers ─────────────────────────────────────────────

const fn parse_u32(s: &str) -> u32 {
    let bytes = s.as_bytes();
    let mut result: u32 = 0;
    let mut i = 0;
    while i < bytes.len() {
        let b = bytes[i];
        assert!(
            b >= b'0' && b <= b'9',
            "PLANTFRIEND_* numeric var must be a non-negative integer"
        );
        result = result * 10 + (b - b'0') as u32;
        i += 1;
    }
    result
}

const fn parse_u8(s: &str) -> u8 {
    let bytes = s.as_bytes();
    let mut result: u8 = 0;
    let mut i = 0;
    while i < bytes.len() {
        let b = bytes[i];
        assert!(
            b >= b'0' && b <= b'9',
            "PLANTFRIEND_* numeric var must be a non-negative integer"
        );
        result = result * 10 + (b - b'0') as u8;
        i += 1;
    }
    result
}

const fn parse_u16(s: &str) -> u16 {
    let bytes = s.as_bytes();
    let mut result: u16 = 0;
    let mut i = 0;
    while i < bytes.len() {
        let b = bytes[i];
        assert!(
            b >= b'0' && b <= b'9',
            "PLANTFRIEND_* numeric var must be a non-negative integer"
        );
        result = result * 10 + (b - b'0') as u16;
        i += 1;
    }
    result
}

const fn parse_u64(s: &str) -> u64 {
    let bytes = s.as_bytes();
    let mut result: u64 = 0;
    let mut i = 0;
    while i < bytes.len() {
        let b = bytes[i];
        assert!(
            b >= b'0' && b <= b'9',
            "PLANTFRIEND_* numeric var must be a non-negative integer"
        );
        result = result * 10 + (b - b'0') as u64;
        i += 1;
    }
    result
}

const fn parse_bool(s: &str) -> bool {
    let b = s.as_bytes();
    b.len() == 4 && b[0] == b't' && b[1] == b'r' && b[2] == b'u' && b[3] == b'e'
}

fn non_empty(value: &'static str) -> Option<&'static str> {
    if value.is_empty() {
        None
    } else {
        Some(value)
    }
}
