// build.rs – project build script
//
// Responsibilities:
//  1. Load the user's .env file (if present) and propagate variables to the
//     compiler environment so that env!() macros in source code resolve them.
//  2. Embed optional TLS certificate/key files as byte arrays via a generated
//     source file written to OUT_DIR.
//  3. Run the embuild / esp-idf-svc link-time setup required for ESP-IDF.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // ── 1. Load .env ─────────────────────────────────────────────────────────
    // Always resolve .env relative to this crate, so workspace-root builds
    // (`cargo build -p esp32c6`) and crate-local builds behave the same.
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR missing");
    let env_path = Path::new(&manifest_dir).join(".env");

    // Collect build-time config vars from .env first, then let process env
    // override them. This allows ad-hoc CI/shell overrides while still working
    // out-of-the-box for local development.
    let mut plantfriend_vars: BTreeMap<String, String> = BTreeMap::new();

    if env_path.exists() {
        match fs::read_to_string(&env_path) {
            Ok(content) => {
                for (idx, raw_line) in content.lines().enumerate() {
                    let line = raw_line.trim();
                    if line.is_empty() || line.starts_with('#') {
                        continue;
                    }

                    let Some((raw_key, raw_value)) = line.split_once('=') else {
                        println!(
                            "cargo:warning=ignoring malformed .env line {} in '{}'",
                            idx + 1,
                            env_path.display()
                        );
                        continue;
                    };

                    let key = raw_key.trim();
                    if !key.starts_with("PLANTFRIEND_") {
                        continue;
                    }

                    let mut value = raw_value.trim().to_string();
                    if value.len() >= 2 {
                        let first = value.as_bytes()[0] as char;
                        let last = value.as_bytes()[value.len() - 1] as char;
                        if (first == '"' && last == '"') || (first == '\'' && last == '\'') {
                            value = value[1..value.len() - 1].to_string();
                        }
                    }

                    plantfriend_vars.insert(key.to_string(), value);
                }
            }
            Err(err) => {
                println!(
                    "cargo:warning=could not read '{}': {err}",
                    env_path.display()
                );
            }
        }
    }

    println!("cargo:rerun-if-changed={}", env_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    // ── 2. Forward PLANTFRIEND_* env vars to rustc ─────────────────────────────
    for (key, value) in env::vars() {
        if key.starts_with("PLANTFRIEND_") {
            plantfriend_vars.insert(key, value);
        }
    }

    for (key, value) in plantfriend_vars {
        env::set_var(&key, &value);
        println!("cargo:rustc-env={key}={value}");
    }

    // ── 3. Generate certs.rs in OUT_DIR ───────────────────────────────────────
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let certs_rs = out_dir.join("certs.rs");

    let ca_cert = read_cert_env("PLANTFRIEND_MQTT_CA_CERT_PATH");
    let client_cert = read_cert_env("PLANTFRIEND_MQTT_CLIENT_CERT_PATH");
    let client_key = read_cert_env("PLANTFRIEND_MQTT_CLIENT_KEY_PATH");

    let certs_content = format!(
        "// Auto-generated by build.rs – do not edit\n\
         pub static MQTT_CA_CERT: Option<&'static [u8]> = {ca};\n\
         pub static MQTT_CLIENT_CERT: Option<&'static [u8]> = {cc};\n\
         pub static MQTT_CLIENT_KEY: Option<&'static [u8]> = {ck};\n",
        ca = bytes_option_literal(&ca_cert),
        cc = bytes_option_literal(&client_cert),
        ck = bytes_option_literal(&client_key),
    );

    fs::write(&certs_rs, certs_content).expect("failed to write certs.rs");

    // ── 4. esp-idf-svc / embuild link configuration ───────────────────────────
    embuild::espidf::sysenv::output();
}

/// Read certificate bytes from the path given by `env_key`, or return None.
fn read_cert_env(env_key: &str) -> Option<Vec<u8>> {
    let path_str = env::var(env_key).unwrap_or_default();
    if path_str.is_empty() {
        return None;
    }
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let path: PathBuf = if Path::new(&path_str).is_absolute() {
        PathBuf::from(&path_str)
    } else {
        Path::new(&manifest_dir).join(&path_str)
    };

    if !path.exists() {
        println!(
            "cargo:warning={env_key} points to '{}' which does not exist – skipping TLS cert",
            path.display()
        );
        return None;
    }

    println!("cargo:rerun-if-changed={}", path.display());
    Some(
        fs::read(&path)
            .unwrap_or_else(|e| panic!("Failed to read certificate '{}': {e}", path.display())),
    )
}

/// Render a Vec<u8> as a Rust `Some(&[...])` or `None` literal.
fn bytes_option_literal(bytes: &Option<Vec<u8>>) -> String {
    match bytes {
        None => "None".to_string(),
        Some(data) => {
            let hex: Vec<String> = data.iter().map(|b| format!("0x{b:02x}")).collect();
            format!("Some(&[{}])", hex.join(", "))
        }
    }
}
