// src/config.rs – compile-time firmware configuration
//
// All values originate from the user's .env file (loaded by build.rs) and are
// resolved at compile time via env!() / option_env!().  This keeps the runtime
// footprint minimal: no SD-card, no NVS parser, no heap allocation needed for
// configuration.
//
// To add a new sensor type (temperature, humidity, pH, etc.) in the future,
// add a corresponding sub-struct here and extend .env.example with the
// relevant HYDROLEVEL_* variables.

// Certificate byte arrays generated by build.rs from the configured cert files.
// When no certs were configured, all entries are None.
include!(concat!(env!("OUT_DIR"), "/certs.rs"));

/// Top-level configuration bundle available throughout the firmware.
pub struct Config {
    pub wifi: WifiConfig,
    pub mqtt: MqttConfig,
    pub sensor: SensorConfig,
    pub publish: PublishConfig,
    pub ha: HaConfig,
    pub ota: OtaConfig,
}

pub struct WifiConfig {
    /// Wi-Fi SSID (network name).
    pub ssid: &'static str,
    /// Wi-Fi pre-shared key / password.
    pub password: &'static str,
}

pub struct MqttConfig {
    /// Full broker URI including scheme and port.
    /// Supported schemes: mqtt://, mqtts://, mqtt5://, mqtt5s://
    pub broker_uri: &'static str,
    /// Optional broker username (empty string = unauthenticated).
    pub username: &'static str,
    /// Optional broker password.
    pub password: &'static str,
    /// MQTT client identifier (must be unique on the broker).
    pub client_id: &'static str,
    /// TLS configuration – None when plain MQTT is used.
    pub tls: Option<TlsConfig>,
}

/// Certificate material embedded at build time.
///
/// Set the corresponding HYDROLEVEL_MQTT_*_PATH variables in .env to enable.
/// Leave all three variables empty for plain-text MQTT.
pub struct TlsConfig {
    /// DER or PEM-encoded CA certificate used to verify the broker.
    pub ca_cert: Option<&'static [u8]>,
    /// Client certificate for mutual TLS (mTLS). Must accompany `client_key`.
    pub client_cert: Option<&'static [u8]>,
    /// Client private key for mutual TLS.
    pub client_key: Option<&'static [u8]>,
}

/// Liquid-level sensor hardware parameters.
pub struct SensorConfig {
    /// GPIO number wired to the sensor's OUTPUT pin.
    pub gpio_pin: u32,
    /// If `true`, a HIGH level means liquid is *present*; otherwise LOW = present.
    pub active_high: bool,
    /// Debounce window in milliseconds.
    pub debounce_ms: u64,
}

/// State-publishing timing.
pub struct PublishConfig {
    /// Heartbeat interval in milliseconds. 0 = on-change only.
    pub interval_ms: u64,
}

/// Home Assistant auto-discovery metadata.
pub struct HaConfig {
    /// HA MQTT discovery prefix (usually "homeassistant").
    pub discovery_prefix: &'static str,
    /// Unique device ID used in all discovery topics.
    pub device_id: &'static str,
    /// Human-readable device name shown in HA UI.
    pub device_name: &'static str,
    /// MQTT topic to which the sensor state is published.
    pub state_topic: &'static str,
    /// MQTT topic for LWT availability messages.
    pub availability_topic: &'static str,
}

/// OTA update behavior.
pub struct OtaConfig {
    /// Optional URL to an OTA app binary.
    pub firmware_url: Option<&'static str>,
    /// Enables automatic OTA apply on boot when a URL is configured.
    pub auto_apply_on_boot: bool,
}

impl Config {
    /// Construct the firmware configuration from compile-time environment
    /// variables.  Panics at compile time if required variables are missing.
    pub fn load() -> Self {
        let tls =
            if MQTT_CA_CERT.is_some() || MQTT_CLIENT_CERT.is_some() || MQTT_CLIENT_KEY.is_some() {
                Some(TlsConfig {
                    ca_cert: MQTT_CA_CERT,
                    client_cert: MQTT_CLIENT_CERT,
                    client_key: MQTT_CLIENT_KEY,
                })
            } else {
                None
            };

        Config {
            wifi: WifiConfig {
                ssid: env!("HYDROLEVEL_WIFI_SSID"),
                password: env!("HYDROLEVEL_WIFI_PASSWORD"),
            },
            mqtt: MqttConfig {
                broker_uri: env!("HYDROLEVEL_MQTT_BROKER_URI"),
                username: option_env!("HYDROLEVEL_MQTT_USERNAME").unwrap_or(""),
                password: option_env!("HYDROLEVEL_MQTT_PASSWORD").unwrap_or(""),
                client_id: env!("HYDROLEVEL_MQTT_CLIENT_ID"),
                tls,
            },
            sensor: SensorConfig {
                gpio_pin: parse_u32(env!("HYDROLEVEL_SENSOR_GPIO")),
                active_high: parse_bool(env!("HYDROLEVEL_SENSOR_ACTIVE_HIGH")),
                debounce_ms: parse_u64(env!("HYDROLEVEL_SENSOR_DEBOUNCE_MS")),
            },
            publish: PublishConfig {
                interval_ms: parse_u64(env!("HYDROLEVEL_PUBLISH_INTERVAL_MS")),
            },
            ha: HaConfig {
                discovery_prefix: env!("HYDROLEVEL_HA_DISCOVERY_PREFIX"),
                device_id: env!("HYDROLEVEL_HA_DEVICE_ID"),
                device_name: env!("HYDROLEVEL_HA_DEVICE_NAME"),
                state_topic: env!("HYDROLEVEL_MQTT_STATE_TOPIC"),
                availability_topic: env!("HYDROLEVEL_MQTT_AVAILABILITY_TOPIC"),
            },
            ota: OtaConfig {
                firmware_url: option_env!("HYDROLEVEL_OTA_URL").and_then(non_empty),
                auto_apply_on_boot: option_env!("HYDROLEVEL_OTA_AUTO_APPLY")
                    .map(parse_bool)
                    .unwrap_or(false),
            },
        }
    }
}

// ── Compile-time parsing helpers ─────────────────────────────────────────────

const fn parse_u32(s: &str) -> u32 {
    let bytes = s.as_bytes();
    let mut result: u32 = 0;
    let mut i = 0;
    while i < bytes.len() {
        let b = bytes[i];
        assert!(
            b >= b'0' && b <= b'9',
            "HYDROLEVEL_* numeric var must be a non-negative integer"
        );
        result = result * 10 + (b - b'0') as u32;
        i += 1;
    }
    result
}

const fn parse_u64(s: &str) -> u64 {
    let bytes = s.as_bytes();
    let mut result: u64 = 0;
    let mut i = 0;
    while i < bytes.len() {
        let b = bytes[i];
        assert!(
            b >= b'0' && b <= b'9',
            "HYDROLEVEL_* numeric var must be a non-negative integer"
        );
        result = result * 10 + (b - b'0') as u64;
        i += 1;
    }
    result
}

const fn parse_bool(s: &str) -> bool {
    let b = s.as_bytes();
    b.len() == 4
        && matches!(
            (
                b.first().copied(),
                b.get(1).copied(),
                b.get(2).copied(),
                b.get(3).copied(),
            ),
            (Some(b't'), Some(b'r'), Some(b'u'), Some(b'e'))
        )
}

fn non_empty(value: &'static str) -> Option<&'static str> {
    if value.is_empty() {
        None
    } else {
        Some(value)
    }
}
