// build.rs – project build script
//
// Responsibilities:
//  1. Load the user's .env file (if present) and propagate variables to the
//     compiler environment so that env!() macros in source code resolve them.
//  2. Embed optional TLS certificate/key files as byte arrays via a generated
//     source file written to OUT_DIR.
//  3. Run the embuild / esp-idf-svc link-time setup required for ESP-IDF.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // ── 1. Load .env ─────────────────────────────────────────────────────────
    let _ = dotenvy::from_filename(".env");

    println!("cargo:rerun-if-changed=.env");
    println!("cargo:rerun-if-changed=build.rs");

    // ── 2. Forward HYDROLEVEL_* env vars to rustc ─────────────────────────────
    for (key, value) in env::vars() {
        if key.starts_with("HYDROLEVEL_") {
            println!("cargo:rustc-env={key}={value}");
        }
    }

    // ── 3. Generate certs.rs in OUT_DIR ───────────────────────────────────────
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let certs_rs = out_dir.join("certs.rs");

    let ca_cert = read_cert_env("HYDROLEVEL_MQTT_CA_CERT_PATH");
    let client_cert = read_cert_env("HYDROLEVEL_MQTT_CLIENT_CERT_PATH");
    let client_key = read_cert_env("HYDROLEVEL_MQTT_CLIENT_KEY_PATH");

    let certs_content = format!(
        "// Auto-generated by build.rs – do not edit\n\
         pub static MQTT_CA_CERT: Option<&'static [u8]> = {ca};\n\
         pub static MQTT_CLIENT_CERT: Option<&'static [u8]> = {cc};\n\
         pub static MQTT_CLIENT_KEY: Option<&'static [u8]> = {ck};\n",
        ca = bytes_option_literal(&ca_cert),
        cc = bytes_option_literal(&client_cert),
        ck = bytes_option_literal(&client_key),
    );

    fs::write(&certs_rs, certs_content).expect("failed to write certs.rs");

    // ── 4. esp-idf-svc / embuild link configuration ───────────────────────────
    embuild::espidf::sysenv::output();
}

/// Read certificate bytes from the path given by `env_key`, or return None.
fn read_cert_env(env_key: &str) -> Option<Vec<u8>> {
    let path_str = env::var(env_key).unwrap_or_default();
    if path_str.is_empty() {
        return None;
    }
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let path: PathBuf = if Path::new(&path_str).is_absolute() {
        PathBuf::from(&path_str)
    } else {
        Path::new(&manifest_dir).join(&path_str)
    };

    if !path.exists() {
        println!(
            "cargo:warning={env_key} points to '{}' which does not exist – skipping TLS cert",
            path.display()
        );
        return None;
    }

    println!("cargo:rerun-if-changed={}", path.display());
    Some(
        fs::read(&path)
            .unwrap_or_else(|e| panic!("Failed to read certificate '{}': {e}", path.display())),
    )
}

/// Render a Vec<u8> as a Rust `Some(&[...])` or `None` literal.
fn bytes_option_literal(bytes: &Option<Vec<u8>>) -> String {
    match bytes {
        None => "None".to_string(),
        Some(data) => {
            let hex: Vec<String> = data.iter().map(|b| format!("0x{b:02x}")).collect();
            format!("Some(&[{}])", hex.join(", "))
        }
    }
}
